DyplomProject/src/assignments/urls.py
from django.urls import path 
from . import views

app_name = 'assignments'

urlpatterns = [
    path('<int:pk>/view-grades/', views.view_grades, name='view_grades'),
    path('<int:pk>/grade/', views.grade, name='grade'),
]

DyplomProject/src/classroom/urls.py
from django.urls import path 
from . import views

app_name = 'classroom'

urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create_classroom, name = 'create_classroom'),
    path('join/', views.join_classroom, name = 'join_classroom'),
    path('open/<int:pk>/', views.open_classroom, name = 'open_classroom'),
    path('<int:pk>', views.delete_classroom, name = 'delete_classroom'),
    path('<int:pk>/leave', views.leave_classroom, name = 'leave_classroom'),
    path('<int:pk>/members', views.members, name = 'members_classroom'),
    path('assignment/<int:pk>/student_work', views.student_work, name = 'student_work'),
    path('assignment/create', views.assignment_create, name = 'assignment_create'),
    path('assignment/<int:pk>', views.assignment_submit, name = 'assignment_submit'),
    path('assignment/<int:pk>/turnin/', views.turnin, name = 'turnin'),
    path('assignment/<int:pk>/unsubmit/', views.unsubmit, name = 'unsubmit'),
    path('assignment/<int:pk>/unsubmit_file/', views.unsubmit_file, name = 'unsubmit_file'),
    path('assignment/<int:pk>/edit/', views.assignment_edit, name = 'assignment_edit'),
    path('assignment/<int:pk>/delete/', views.assignment_delete, name = 'assignment_delete'),
    path('todo/', views.todo, name = 'todo'),
    path('toreview/', views.toreview, name = 'toreview'),
    path('<int:pk>/classwork/', views.classwork, name = 'classwork'),
]

DyplomProject/src/comments/urls.py
from django.urls import path, include
from . import views

app_name = 'comments'

urlpatterns = [
    path('create/<int:post_pk>/', views.create_post_comment, name='create_post_comment'),
    path('assignment_comment/create/<int:assignment_pk>/', views.create_assignment_comment, name='create_assignment_comment'),
]

DyplomProject/src/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views


from . import views


urlpatterns = [
    path('comments', include('comments.urls')),
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls')),
    path('', views.landing, name='landing-page'),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('assignments/', include('assignments.urls')),
    path('schedule/', include('schedule.urls')),
    path('journal/', include('journal.urls')),
    path('password-reset/', 
    auth_views.PasswordResetView.as_view(
        template_name = 'users/password_reset.html'),
        name = 'password_reset'
    ),
    path('password-reset/done/', 
    auth_views.PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'),
        name = 'password_reset_done'
    ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
    ),
        name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
    ),
      name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DyplomProject/src/posts/urls.py
from django.urls import path 
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/<int:pk>/', views.create_post, name='create_post'),
    path('edit/<int:pk>/', views.edit_post, name='edit_post'),
    path('delete/<int:pk>/', views.delete_post, name='delete_post'),
]

DyplomProject/src/classroom/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import string
import random


class Classroom(models.Model):
    name = models.CharField(max_length=200, unique=True)
    classroom_code = models.CharField(max_length=20, blank=True)
    description = models.TextField(max_length=300)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(default=timezone.now)
    users = models.ManyToManyField(User, related_name='classrooms', through='ClassroomUsers')

    @staticmethod
    def generate_code(length=6):
        letters_and_digits = string.ascii_letters + string.digits
        return ''.join(random.choice(letters_and_digits) for i in range(length))

    def __str__(self):
        return f'{self.name}'


class ClassroomTeachers(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.teacher.username} -> {self.classroom.name}'


class ClassroomUsers(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name} -> {self.classroom.name}'

    class Meta:
        db_table = "classroom_classroom_users"
        unique_together = ('classroom', 'user')


class Topic(models.Model):
    name = models.CharField(max_length=200)
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.classroom.name} -> {self.name}'

DyplomProject/src/classroom/forms.py
from django.forms import ModelForm
from django import forms
from .models import Classroom
from posts.models import Assignment


class ClassroomCreationForm(ModelForm):
    class Meta:
        model = Classroom
        fields = ['name', 'description']


class JoinClassroomForm(forms.Form):
    code = forms.CharField(label='Введіть код', max_length=100)


class PostForm(forms.Form):
    title = forms.CharField()
    description = forms.CharField(widget=forms.Textarea)
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)
    owerride_files = forms.BooleanField(widget=forms.CheckboxInput, required=False)


class AssignmentFileForm(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))


class AssignmentCreateForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        super(AssignmentCreateForm, self).__init__(*args, **kwargs)
        classrooms = list(map(lambda x: x.classroom, user.classroomteachers_set.all()))
        topics = []
        self.fields['classrooms'].choices = [(str(classroom.pk),classroom.name) for classroom in classrooms]
        for classroom in classrooms:
            topics.extend(list(classroom.topic_set.all()))
        self.fields['topics'].choices = [(str(topic.pk),f"{topic.name}->{topic.classroom.name}") for topic in topics]

    title = forms.CharField()
    description = forms.CharField(widget=forms.Textarea)
    classrooms = forms.ChoiceField()
    topics = forms.ChoiceField()
    points = forms.IntegerField(min_value=0, max_value=12)
    due_date = forms.DateTimeField()
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)
    owerride_files = forms.BooleanField(widget=forms.CheckboxInput, required=False)

DyplomProject/src/classroom/views.py
from django.utils import timezone

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required


from .models import Classroom, Topic, ClassroomTeachers
from posts.models import Assignment,SubmittedAssignment,AssignmentFile, Attachment, Post
from .forms import ClassroomCreationForm,JoinClassroomForm, PostForm, AssignmentFileForm, AssignmentCreateForm
from comments.forms import CommentCreateForm


@login_required
def home(request):
    teaching_classes = request.user.classroomteachers_set.all()
    student_classes = request.user.classrooms.all()
    classroom_form = ClassroomCreationForm()
    join_classroom_form = JoinClassroomForm()
    context = {
        'teaching_classes': teaching_classes,
        'student_classes': student_classes,
        'classroom_form': classroom_form,
        'join_classroom_form': join_classroom_form
    }
    return render(request, 'classroom/home.html', context)


@login_required
@permission_required("classroom.add_classroom", raise_exception=True)
def create_classroom(request):
    if request.method == 'POST':
        form = ClassroomCreationForm(request.POST)
        if form.is_valid(): 
            name = form.cleaned_data.get('name')
            description = form.cleaned_data.get('description')
            classroom = Classroom(name=name, description=description, created_by=request.user,
                                  classroom_code=Classroom.generate_code())
            classroom.save()
            topic = Topic(name='General', classroom=classroom)
            topic.save()
            classroom_teachers = ClassroomTeachers(classroom=classroom, teacher=request.user)
            classroom_teachers.save()
            messages.success(request, f'Classroom {name} created !')
        else:
            messages.warning(request, f'Classroom Could not be created :(')
    return redirect('classroom:home')


@login_required
def join_classroom(request):
    if request.method == 'POST':
        form = JoinClassroomForm(request.POST)
        if form.is_valid(): 
            classroom = Classroom.objects.filter(classroom_code = form.cleaned_data.get('code')).first()
            if classroom:
                request.user.classrooms.add(classroom)
                messages.success(request, f'You are added in {classroom.name}')
            else:
                messages.warning(request, f'Помилка приєднання вас до класу')
        else:
            messages.warning(request, f'Помилка приєднання вас до класу')
    return redirect('classroom:home')


@login_required
def open_classroom(request, pk):
    classroom = get_object_or_404(Classroom, pk=pk)
    if request.user in [clt.teacher for clt in classroom.classroomteachers_set.all()] or request.user in classroom.users.all():
        topics = classroom.topic_set.all()
        contents = []
        for topic in topics:
            contents.extend(list(topic.post_set.all()))
            contents.extend(list(topic.assignment_set.all()))

        contents.sort(key=lambda x: x.created_at)

        post_form = PostForm()
        comment_form = CommentCreateForm()
        context = {
            'teachers': classroom.classroomteachers_set.all(),
            'students': classroom.users.all(),
            'classroom': classroom,
            'contents': reversed(contents),
            'post_form': post_form,
            'comment_form': comment_form,
        }

        return render(request, 'classroom/classroom.html', context)
    messages.warning(request, f'Ви не є учасником цього класу!')
    return redirect('classroom:home')


@login_required
def leave_classroom(request, pk):
    classroom = get_object_or_404(Classroom, pk=pk)
    if request.user in classroom.users.all():
        request.user.classrooms.remove(classroom)
        messages.success(request, f'Ви покинули клас!')
    else:
        messages.warning(request, f'Ви не є учасником цього класу!')

    return redirect('classroom:home')


@login_required
@permission_required("classroom.delete_classroom", raise_exception=True)
def delete_classroom(request, pk):
    classroom = get_object_or_404(Classroom, pk=pk)
    if request.user in [clt.teacher for clt in classroom.classroomteachers_set.all()]:
        classroom.delete()
        messages.success(request, f'Клас успішно видалено.')
    else:
        messages.warning(request, f'Ви не можете видалити клас! Це може зробити тільки вчитель!')
    return redirect('classroom:home')


@login_required
def members(request, pk):
    classroom = get_object_or_404(Classroom, pk=pk)
    context = {
        'teachers': classroom.classroomteachers_set.all(),
        'students': classroom.users.all(),
    }
    return render(request, 'classroom/members.html', context)


@login_required
@permission_required("posts.add_assignment", raise_exception=True)
def assignment_create(request):
    if request.method == 'POST':
        form = AssignmentCreateForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            topic = get_object_or_404(Topic, pk=int(form.cleaned_data['topics']))
            assignment = Assignment(
                title = form.cleaned_data['title'],
                description = form.cleaned_data['description'],
                created_by = request.user,
                topic = topic,
                due_date = form.cleaned_data['due_date']
            )
            assignment.save()
            files = request.FILES.getlist('file_field')
            for f in files:
                Attachment.objects.create(assignment = assignment,files=f)
                messages.success(request, f'Завдання успішно створено!')
            return redirect('classroom:open_classroom', topic.classroom.pk)
    else:
        form = AssignmentCreateForm(request.user, request.GET)
    context = {'form': form}
    return render(request, 'classroom/assignment_create.html', context)


@login_required
def assignment_submit(request, pk):
    if request.method == 'POST':
        assignment = get_object_or_404(Assignment,pk=pk)
        submitted_assignment = assignment.submittedassignment_set.filter(user = request.user).first()
        if not submitted_assignment:
            submitted_assignment = SubmittedAssignment.objects.create(assignment = assignment, user = request.user)
        files = request.FILES.getlist('file_field')
        for f in files:
            AssignmentFile.objects.create(submitted_assignment = submitted_assignment,files=f)
        submitted_assignment.turned_in = True
        submitted_assignment.save()
        messages.success(request, f'Завдання успішно подано на перевірку!')
    
    form = AssignmentFileForm()
    comment_form = CommentCreateForm()
    assignment = get_object_or_404(Assignment, pk=pk)
    submit_assignment = assignment.submittedassignment_set.filter(user=request.user)
    classroom_teachers = list(map(lambda teaches: teaches.teacher, assignment.topic.classroom.classroomteachers_set.all()))
    is_teacher = request.user in classroom_teachers
    if submit_assignment:
        submit_assignment = submit_assignment.first()
        assignment_files = submit_assignment.assignmentfile_set.all()
    else:
        assignment_files = None

    context = {
        'assignment': assignment,
        'attachments': assignment.attachment_set.all(),
        'submitted_assignment': submit_assignment,
        'assignment_files': assignment_files,
        'form': form,
        'comment_form': comment_form,
        'is_teacher': is_teacher,
    }
    return render(request, 'classroom/assignment_submit.html', context)


@login_required
@permission_required("posts.change_assignment", raise_exception=True)
def assignment_edit(request, pk):
    assignment = get_object_or_404(Assignment, pk=pk)
    if request.method == 'POST':
        form = AssignmentCreateForm(user=request.user, data=request.POST, files=request.FILES,
                                    initial={'title': assignment.title,
                                             'description': assignment.description,
                                             'topics': assignment.topic.pk,
                                             'due_date': assignment.due_date.strftime(
                                                '%Y-%m-%dT%H:%M'),
                                             'classrooms': assignment.topic.classroom.pk,
                                             'points': assignment.marks})

        if form.is_valid():
            topic = get_object_or_404(Topic, pk=int(form.cleaned_data['topics']))
            assignment.title = form.cleaned_data['title']
            assignment.description = form.cleaned_data['description']
            assignment.topic = topic
            assignment.due_date = form.cleaned_data['due_date']
            assignment.save()
            files = request.FILES.getlist('file_field')
            if form.cleaned_data.get('owerride_files'):
                for resource in assignment.resources:
                    resource.delete()
            for f in files:
                Attachment.objects.create(assignment=assignment, files=f)
            messages.success(request, f'Завдання успішно відредаговано.')
            return redirect('classroom:open_classroom', topic.classroom.pk)
    else:
        form = AssignmentCreateForm(user=request.user, initial={'title': assignment.title,
                                                                'description': assignment.description,
                                                                'topics': assignment.topic.pk,
                                                                'due_date': assignment.due_date.strftime('%Y-%m-%dT%H:%M'),
                                                                'classrooms': assignment.topic.classroom.pk,

DyplomProject/src/classroom/templates/classroom/assignment_submit.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %} Завдання {% endblock title %}

{% block content %}
<div class="row m-2">
    {% if request.user.profile.is_teacher %}
    <div class="col-lg-8" style="position: relative; left: 180px">
    {% else %}
    <div class="col-lg-8">
    {% endif %}
        <div class="row">
            <img src="{% static 'mainapp/img/assignment.png' %}" width="45" height="45"
                                                     alt="..." class="rounded-circle mr-2 mb-2 float-left">
            <h3 class="text-primary">{{ assignment.title }}</h3>
              {% if request.user.profile.is_teacher %}
                <div class="dropdown no-arrow ml-auto">
                  <a class="btn btn-circle dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-dark"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'classroom:assignment_edit' assignment.pk %}">
                        <i class="fas fa-edit"></i>
                        <span>Редагувати завдання</span>
                    </a>
                    <a class="dropdown-item" href="{% url 'classroom:assignment_delete' assignment.pk %}">
                        <i class="fas fa-trash-alt"></i>
                        <span>Видалити завдання</span>
                    </a>
                  </div>
                </div>
              {% endif %}
          </div>
          <div class="row">
            <p class="text-muted">{{ assignment.created_by.first_name }} {{ assignment.created_by.last_name }}
                <i class="fas fa-circle fa-xs"></i>
                {{ assignment.created_at }}
          </div>
          <div class="row">
            <p class="text-dark font-weight-bold">Максимальна оцінка {{ assignment.marks }} балів</p>
            <p class="ml-auto text-dark font-weight-bold">Потрібно виконати до {{ assignment.due_date }}</p>
          </div>
          <hr>
          <p>{{ assignment.description }}</p>
          <div class="row">
            {% for resource in assignment.resources %}
            <div class="col-6">
                <div class="card mb-3 ml-2">
                    <div class="row no-gutters">
                        <div class="col-md-3">
                        <img src="{% static 'mainapp/img/file1.png' %}" class="card-img img-fluid d-none d-lg-block" alt="...">
                        </div>
                        <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title "><a target="_blank" href="{{ resource.files.url  }}">{{ resource.filename|truncatechars:15 }}</a>
                            </h5>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <hr>
        <div class="card-body">
            {% for comment in assignment.comments %}
                <div class="d-flex flex-row">
                    <img src="{{ comment.user.profile.image.url }}" width="35"
                         height="35" alt="..." class="rounded-circle mr-2">
                    <p class='ml-2'>
                        <strong>{{ comment.user.first_name }} {{ comment.user.last_name }}</strong>: {{ comment.comment_text }}
                    </p>
                </div>
            {% endfor %}
        </div>
        <hr>
        <div class="card-body">
            <form action="{% url 'comments:create_assignment_comment' assignment.pk %}"
                  method="post">
                <div class="input-group">
                    <img src="{{ request.user.profile.image.url }}" width="35" height="35" alt="..." class="rounded-circle ml-2 mr-2">
                    {% csrf_token %}
                    {{ comment_form.comment_text|attr:"class:form-control rounded-pill"|attr:"placeholder:Додайте коментар" }}
                    <div class="input-group-append">
                        <button class=" btn btn-circle" type="submit"
                                id="button-addon2"><i
                                class="fas fa-angle-double-right"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    {% if request.user.profile.is_student %}
    <!-- The Submit cards -->
    <div class="col-lg-4">
      <div class="card p-4 m-3 shadow">
        
        <div class="row">
          <h4 class="text-primary">Твоя робота</h4>
              {% if submitted_assignment %}

                {% if submitted_assignment.turned_in %}
                <p class="ml-auto text-success">
                    Здано
                </p>  
                      
                {% else %}
                <p class="ml-auto text-success">
                    Призначено
                </p>
                {% endif %}
              {% else %}
                <p class="ml-auto text-success">
                    Призначено
                </p>
              {% endif %}

        </div>
        {% if submitted_assignment and submitted_assignment.is_reviewed %}
            <div >

              <p class="ml-auto text-secondary">
                Оцінено :
                {{ submitted_assignment.grade }}
              </p>
            </div>
        {% endif %}
        {% if submitted_assignment %}
            {% if assignment_files %}
                <p>Подані файли</p>
                {% for file in assignment_files %}
                  <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div class="col-md-4">
                            <img src="{% static 'mainapp/img/file1.png' %}" class="card-img " alt="...">
                        </div>
                        <a href="{{ file.files.url }}">{{ file.filename|truncatechars:12 }}</a>
                        <form action="{% url 'classroom:unsubmit_file' file.pk %}" method="post">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-circle">X</button>
                        </form>
                    </li>
                  </ul>
                {% endfor %}
            {% endif %}
            {% if not submitted_assignment.turned_in %}
                <form action="{% url 'classroom:assignment_submit' assignment.pk %}" method="post" enctype='multipart/form-data'>
                  {% csrf_token %}
                  {{ form | crispy }}
                  <button type="submit" class="btn btn-outline-dark btn-block m-1">
                      <i class="fa fa-plus" aria-hidden="true"></i> Здати роботу
                  </button>
                </form>
                <form action="{% url 'classroom:turnin' assignment.pk %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-primary btn-block m-1">Позначити як виконане</button>
                </form>
            {% else %}
                <form action="{% url 'classroom:unsubmit' assignment.pk %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-outline-dark btn-block m-1">Скасувати надсилання</button>
                </form>
            {% endif %}
        {% else %}
            <form action="{% url 'classroom:assignment_submit' assignment.pk %}" method="post"  enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-outline-dark btn-block m-1">
                    <i class="fa fa-plus" aria-hidden="true"></i> Здати роботу
                </button>
            </form>
            <form action="{% url 'classroom:turnin' assignment.pk %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary btn-block m-1">Позначити як виконане</button>
            </form>
        {% endif %}

      </div>
    </div>
    {% endif %}
</div>
{% endblock %}

DyplomProject/src/classroom/templates/classroom/classwork.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %} Classwork {% endblock title %}

{% block content %}
<style media="screen">
    .card:hover {
      transform: scale(1);
      box-shadow: 0 5px 5px rgba(0, 0, 0, .12), 0 4px 8px rgba(0, 0, 0, .06);
    }
</style>
<div class="row">

<div class="col-12">
    <div class="accordion" id="accordionExample">
        <!-- first card -->
<!--        <div class="col-9 mx-auto mb-5">-->
<!--            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Створити</button>-->
<!--            <div class="dropdown-menu">-->
<!--              <a class="dropdown-item" href="{% url 'classroom:assignment_create' %}">Assignment</a>-->
<!--            </div>-->
<!--        </div>-->
<!--        <br>-->
        {% for assignment in assignments %}
        <div class="col-lg-9 mx-auto">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="" id="headingOne">
                    <div class="card" type="card" data-toggle="collapse" data-target="#collapse{{ assignment.pk }}" aria-expanded="true" aria-controls="collapseOne">
                        <div class="card-body">
                        <i class="fas fa-clipboard"></i> 
                        <a class="text-decoration-none" href="{% url 'classroom:assignment_submit' assignment.pk %}">{{ assignment.title }}</a>
                        
                        <em class="text-muted d-inline float-right">Потрібно виконати до {{ assignment.due_date }}</em>
                        </div>
                    </div>
                    </div>

                    <div id="collapse{{ assignment.pk }}" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="row">
                            {% for resource in assignment.resources %}
                                <div class="col-6">
                                    <div class="card mb-3 ml-2" style="max-width: 400px; max-height:100px;">
                                        <div class="row no-gutters">
                                            <div class="col-md-4">
                                                <img src="{% static 'mainapp/img/file1.png' %}" style="width: 60px" class="card-img img-fluid d-none d-lg-block" alt="...">
                                            </div>
                                            <div class="col-md-8">
                                                <div class="card-body">
                                                <h5 class="card-title "><a href="{{ resource.files.url }}">{{ resource.filename }}</a>
                                                </h5>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <!-- end first card -->
    </div>
</div>
 
{% endblock content %}

DyplomProject/src/classroom/templates/classroom/toreview.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %} Перевірка завдань {% endblock title %}

{% block content %}
<div class = "ml-lg-5 mr-lg-5">
    <div class="accordion" id="accordionExample">
      {% for assignment in assignments %}
        <!-- CARD -->
        <div class="card mb-2">
          <div class="card-header" id="headingOne">
            <h2 class="mb-0">
              <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse{{ assignment.pk }}" aria-expanded="true" aria-controls="collapseOne">
                {{ assignment.title }}
              </button>
            </h2>
          </div>
          <div id="collapse{{ assignment.pk }}" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
               <small>Опубліковано {{ assignment.created_at }}</small>
               <p>{{ assignment.description }}</p>
               <div class = "d-flex flex-row-reverse">
                    <div class="p-2 border-left border-secondary">
                        <h1 class="text-dark">{{ assignment.total_turned_in  }}</h1>
                        <br>
                        <p>Здали</p>
                    </div>
                    <div class="p-2 border-left border-secondary">
                        <h1 class="text-dark">{{ assignment.total_missing }}</h1>
                        <br>
                        <p>Не здали</p>
                    </div>
               </div>
            <hr>
            <div class="d-flex flex-row bd-highlight mb-3">
                <a class = "p-2" href = "{% url 'classroom:assignment_submit' assignment.pk %}" >Переглянути завдання</a>
                <a class = "p-2" href = "{% url 'classroom:student_work' assignment.pk %}" >Переглянути роботу учня</a>
                <a class = "p-2" href = "{% url 'assignments:view_grades' assignment.pk %}" >Переглянути оцінки</a>
            </div>
          </div>
        </div>
      </div>
      <!-- END CARD -->
      {% endfor %}
</div>


{% endblock %}