DyplomProject/src/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views


from . import views


urlpatterns = [
    path('comments', include('comments.urls')),
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls')),
    path('', views.landing, name='landing-page'),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('assignments/', include('assignments.urls')),
    path('schedule/', include('schedule.urls')),
    path('journal/', include('journal.urls')),
    path('password-reset/', 
    auth_views.PasswordResetView.as_view(
        template_name = 'users/password_reset.html'),
        name = 'password_reset'
    ),
    path('password-reset/done/', 
    auth_views.PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'),
        name = 'password_reset_done'
    ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
    ),
        name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
    ),
      name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DyplomProject/src/journal/urls.py
from django.urls import path
from . import views

app_name = 'journal'

urlpatterns = [
    path('', views.view_journal_list, name='view_list'),
    path('<int:classroom_id>', views.view_journal, name='view_teacher_journal'),
    path('add_grade/', views.add_grade, name='add_grade'),
]

DyplomProject/src/journal/models.py
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models, connection
from classroom.models import ClassroomUsers


class Rating(models.IntegerChoices):
    dont_visited = 0
    one = 1
    two = 2
    three = 3
    four = 4
    five = 5
    six = 6
    seven = 7
    eight = 8
    nine = 9
    ten = 10
    eleven = 11
    twelve = 12


class Journal(models.Model):
    rating = models.IntegerField(choices=Rating.choices)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    created_at = models.DateField(default=timezone.now)
    classroom_user = models.ForeignKey(ClassroomUsers, on_delete=models.CASCADE)
    topik = models.CharField(max_length=200)

    class Meta:
        unique_together = ('classroom_user', 'created_at')

    @staticmethod
    def get_student_rating(student_id: int, classroom_id: int):
        with connection.cursor() as cursor:
            sql_query = f"""
                SELECT j.id , j.rating, j.created_at, j.topik, t.last_name ||' '||t.first_name as teacher, classroom.name
                FROM journal_journal as j
                INNER JOIN auth_user as t
                    ON t.id = j.created_by_id
                INNER JOIN classroom_classroom_users as classroom_users
                    ON classroom_users.id = j.classroom_user_id
                INNER JOIN auth_user as student
                    ON student.id = classroom_users.user_id
                INNER JOIN classroom_classroom as classroom
                    ON classroom.id = classroom_users.classroom_id
                WHERE student.id = {student_id} and classroom.id = {classroom_id};
            """
            cursor.execute(sql_query)
            results = Journal.dict_fetchall(cursor)
        return results

    @staticmethod
    def get_list_students_in_classroom(classroom_id: int):
        with connection.cursor() as cursor:
            sql_query = f"""
                SELECT au.id user_id, au.username, au.first_name, au.last_name, cu.id classroom_users_id
                FROM classroom_classroom_users cu
                INNER JOIN auth_user au ON au.id = cu.user_id 
                WHERE cu.classroom_id = {classroom_id}
                GROUP BY user_id;
            """
            cursor.execute(sql_query)
            results = Journal.dict_fetchall(cursor)
        return results

    @staticmethod
    def get_list_student_classroom(student_id: int):
        with connection.cursor() as cursor:
            sql_query = f"""
                SELECT classroom.id, classroom.name, classroom.description, classroom.created_at 
                FROM classroom_classroom_users classroom_users 
                INNER JOIN classroom_classroom classroom on classroom.id = classroom_users.classroom_id
                WHERE classroom_users.user_id = {student_id};
            """
            cursor.execute(sql_query)
            results = Journal.dict_fetchall(cursor)
        return results

    @staticmethod
    def get_list_teacher_classroom(teacher_id: int):
        with connection.cursor() as cursor:
            sql_query = f"""
                SELECT classroom.id as classroom_id, classroomteachers.teacher_id, classroom.name , classroom.classroom_code, classroom.created_at 
                FROM classroom_classroomteachers classroomteachers
                INNER JOIN classroom_classroom classroom on classroom.id = classroomteachers.classroom_id
                WHERE classroomteachers.teacher_id = {teacher_id}
                GROUP BY classroom.id
            """
            cursor.execute(sql_query)
            results = Journal.dict_fetchall(cursor)
        return results

    @staticmethod
    def get_rating_date(date: str, user_id: int, classroom_id: int):
        with connection.cursor() as cursor:
            sql_query = f"""
                SELECT *
                FROM journal_journal jj
                INNER JOIN classroom_classroom_users cu 
                    on cu.id = jj.classroom_user_id 
                WHERE 
                    jj.created_at = '{date}' AND
                    cu.user_id = {user_id} AND
                    cu.classroom_id = {classroom_id};
            """
            cursor.execute(sql_query)
            results = Journal.dict_fetchall(cursor)
        return results

    def __str__(self):
        return f'{self.classroom_user} -> {self.topik}'

    @staticmethod
    def dict_fetchall(cursor):
        columns = [col[0] for col in cursor.description]
        rows = cursor.fetchall()

        results = []
        for row in rows:
            results.append(dict(zip(columns, row)))

        return results


"""
SELECT *
FROM journal_journal jj
INNER JOIN classroom_classroom_users cu 
	on cu.id = jj.classroom_user_id 
WHERE 
	jj.created_at >= '2023-06-18' AND
	jj.created_at <= '2023-06-19' AND
	cu.user_id = 14
"""

DyplomProject/src/journal/forms.py
from django.forms import ModelForm
from django import forms
from .models import Journal


class AddGradeForm(ModelForm):
    class Meta:
        model = Journal
        fields = ['topik', 'rating', 'created_at', 'classroom_user']

        widgets = {
            'created_at': forms.widgets.DateInput(attrs={'type': 'hidden'}),
            'classroom_user': forms.TextInput(attrs={'type': 'hidden'}),
        }

DyplomProject/src/journal/views.py
import datetime
import locale

from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from classroom.models import Classroom
from .models import Journal
from .forms import AddGradeForm


@login_required
def view_journal_list(request):
    if request.user.profile.is_teacher():
        list_classroom = Journal.get_list_teacher_classroom(teacher_id=request.user.id)
    else:
        list_classroom = Journal.get_list_student_classroom(student_id=request.user.id)

    return render(
        request=request,
        template_name='journal/journal_list.html',
        context={'list_classroom': list_classroom}
    )


def view_journal(request, classroom_id: int):
    if request.user.profile.is_teacher():
        start_date = str(request.GET.get("start_date", datetime.date.today()))
        start_date = datetime.datetime.strptime(start_date, '%Y-%m-%d').date()
        date_list = []

        for x in range(7):
            date = start_date + datetime.timedelta(days=x)
            if date.weekday() < 5:
                date_list.append(date)

        students_list = Journal.get_list_students_in_classroom(classroom_id=classroom_id)

        for student in students_list:
            date_rating = []
            for d in date_list:
                date_rating.append(
                    (str(d), Journal.get_rating_date(str(d), student["user_id"], classroom_id))
                )
            student['rating'] = date_rating
        add_grade_form = AddGradeForm()
        classroom = get_object_or_404(Classroom, id=classroom_id)
        class_name = classroom.name
        return render(
            request=request,
            template_name='journal/journal_teacher.html',
            context={'students_list': students_list, 'add_grade_form': add_grade_form, 'class_name': class_name}
        )
    else:
        rating = Journal.get_student_rating(
            student_id=request.user.id,
            classroom_id=classroom_id
        )

        return render(
            request=request,
            template_name='journal/journal_student_rating.html',
            context={'rating': rating}
        )


@login_required
def add_grade(request):
    if request.method == 'POST':
        form = AddGradeForm(request.POST)
        if form.is_valid():
            topik = form.cleaned_data.get('topik')
            rating = form.cleaned_data.get('rating')
            created_at = form.cleaned_data.get('created_at')
            classroom_user = form.cleaned_data.get('classroom_user')

            Journal(
                rating=rating,
                created_at=created_at,
                classroom_user=classroom_user,
                created_by=request.user, topik=topik
            ).save()

            messages.success(request, f'Оцінка додана!')

        else:
            messages.warning(request, f'Помилка додавання оцінки:(')

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

DyplomProject/src/journal/templates/journal/group_list.html
{% extends "base.html" %}

{% block title %}Журнал{% endblock %}

{% block content %}
<h1>Журнал</h1>
<!--<ul>-->
<!--    {% for item in rating %}-->
<!--    <li>{{ item }}</li>-->
<!--    {% endfor %}-->
<!--</ul>-->


<table class="table table-bordered">
    <thead>
    <tr>
        <th>Заняття</th>
        <th>Тема Уроку</th>
        <th>Дата</th>
        <th>Оцінка</th>
        <th>Вчитель</th>
    </tr>
    </thead>
    <tbody>
    {% for item in rating %}
    <tr>
        <td>{{item.name}}</td>
        <td>{{item.topik}}</td>
        <td>{{item.created_at}}</td>
        <td>{% if item.rating == 0 %} <b>н/н</b> {% elif item.rating == 13 %} <b></b> {% else %} {{item.rating}} {% endif%}</td>
        <td>{{item.teacher}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

DyplomProject/src/journal/templates/journal/journal_list.html
{% extends "base.html" %}

{% block title %}Журнал{% endblock %}

{% block content %}
<h1>Список журналів класів</h1>

<!--{{user.id}}-->
<!--is_teacher:{{user.profile.is_teacher}}-->
<!--<ul>-->
<!--    {% for item in list_classroom %}-->
<!--    <li>{{ item }}</li>-->
<!--    {% endfor %}-->
<!--</ul>-->

{% if user.profile.is_teacher  %}
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Назва предмету</th>
        <th>Дата створення</th>
    </tr>
    </thead>
    <tbody>
    {% for item in list_classroom %}
    <tr>
        <td><b><a href="{{item.classroom_id}}">{{item.name}}</a></b></td>
        <td>{{item.created_at}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Назва предмету</th>
        <th>Вчитель</th>
        <th>Дата створення</th>
    </tr>
    </thead>
    <tbody>
    {% for item in list_classroom %}
    <tr>
        <td><b><a href="{{item.id}}">{{item.name}}</a></b></td>
        <td>{{item.description}}</td>
        <td>{{item.created_at}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endif %}

{% endblock %}

DyplomProject/src/journal/templates/journal/journal_student_rating.html
{% extends "base.html" %}

{% block title %}Журнал{% endblock %}

{% block content %}
<h1><b>Урок:</b> {{rating.0.name}}</h1>


<table class="table table-bordered">
    <thead>
    <tr>
        <th>Тема уроку</th>
        <th>Дата уроку</th>
        <th>Оцінка</th>
        <th>Вчитель</th>
    </tr>
    </thead>
    <tbody>
    {% for item in rating|dictsort:"created_at" %}
    <tr>
        <td>{{item.topik}}</td>
        <td>{{item.created_at}}</td>
        <td>{% if item.rating == 0 %} <b>н/н</b> {% else %} {{item.rating}} {% endif%}
        </td>
        <td>{{item.teacher}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

DyplomProject/src/journal/templates/journal/journal_teacher.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %}Журнал{% endblock %}

{% block content %}
<h1><b>Журнал:</b> {{ class_name }}</h1>

<form action="" method="get">
    <label for="start_date">Показати оцінки починаючи з дати:</label>
    <div class="d-inline-block">
        <input type="date" class="form-control" style="width: 200px" id="start_date"  name="start_date" required>
    </div>
    <div class="d-inline-block">
        <input type="submit" class="btn btn-primary" value="Показати">
    </div>
</form>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>№</th>
        <th>Прізвище Ім'я</th>
        {% for item in students_list.0.rating %}
        <th>{{item.0}}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for student in students_list|dictsort:"last_name" %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{student.last_name}} {{student.first_name}}</td>
        {% for rating in student.rating %}
        <th class="text-center">
            {% if rating.1.0|length > 0 %}
                {% if rating.1.0.rating == 0 %}
                    <span>н/н</span>
                {% else %}
                    {{rating.1.0.rating}}
                {% endif %}
            {% else %}
            <button type="button" data-toggle="modal" data-target="#addgradeModal" class="btn btn-outline-light"
                    onclick="changeRatingForm('{{rating.0}}','{{student.classroom_users_id}}')">
                <i class="fas fa-plus"></i>
            </button>
            {% endif %}
        </th>
        {% endfor %}
    </tr>
    {% endfor %}
    </tbody>
</table>

<div class="modal fade" id="addgradeModal" tabindex="-1" role="dialog" aria-labelledby="addgradeModalTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addgradeModalLongTitle">Додати оцінку</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'journal:add_grade' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="topik">Тема уроку:</label>
                        {{ add_grade_form.topik|attr:'class: form-control'|attr:"placeholder:Введіть тему уроку" }}
                    </div>
                    <div class="form-group">
                        <label for="rating">Оцінка</label>
                        {{ add_grade_form.rating|attr:'class: form-control' }}
                    </div>
                        {{ add_grade_form.created_at }}
                        {{ add_grade_form.classroom_user }}
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                    <button type="submit" class="btn btn-primary">Додати оцінку</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
function changeRatingForm(created_at, classroom_user) {
    console.log(created_at, classroom_user);
    document.getElementById("id_created_at").value = created_at;
    document.getElementById("id_classroom_user").value = classroom_user;
}
</script>
{% endblock %}